### PR TITLE
refactor: upgrade go version to 1.18.6

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

Related to https://github.com/jenkins-x/jx/issues/8283

### CODE REVIEW

**Review by tomhobson — APPROVED** [review]

**Comment by tomhobson** [comment]
@ankitm123 can you sort out the OWNERS file in the PR as well

**Comment by ankitm123** [comment]
> @ankitm123 can you sort out the OWNERS file in the PR as well

It's done in this PR, so once this is in master/main, we should be good!

**Comment by ankitm123** [comment]
Related to https://github.com/jenkins-x/jx/issues/8283

**Pull request merged**
